# Neo4j Community 5.26.30, built from this fork (PMOVES.AI-Edition-5.26 = upstream tag 5.26.30).
#
# The official neo4j image is assembled from three repositories; this Dockerfile builds all three:
#   1. neo4j/neo4j (this repo, GPL-3.0)  -> Maven -> neo4j-community-5.26.30-unix.tar.gz
#   2. neo4j/apoc  (Apache-2.0)          -> Gradle -> apoc-5.26.30-core.jar, placed in labs/ as the release does
#   3. neo4j/docker-neo4j (Apache-2.0)   -> the runtime stage below and docker/local-package/, vendored from
#      tag neo4j-5.26.30 (d00c64fde2cc0939c103408e0338ab1b3c29f4c0). See docker/UPSTREAM.md.
# Stage 3 is docker-image-src/5/coredb/Dockerfile-trixie at that tag, generated by docker/render-dockerfile.py.
# Its only changes: the tarball comes from stage 1 instead of a download from dist.neo4j.org, the APOC core jar
# comes from stage 2, base images are digest-pinned, and OCI labels are added. Everything else, including the
# vendor's permission model, is kept byte-for-byte so the A/B against neo4j:5.26.30-community compares builds,
# not packaging choices.
#
# Version: the upstream tag's poms say 5.26.30-SNAPSHOT (161 poms). The vendor release pipeline rewrites them;
# so does stage 1 (`versions:set`), so the jars' Implementation-Version (addDefaultImplementationEntries,
# pom.xml:425), `neo4j --version` and the Bolt server agent read 5.26.30 like the vendor image.
#
# Base images are pinned by multi-arch index digest (resolved 2026-10-01).
ARG MAVEN_IMAGE=maven:3.9.11-eclipse-temurin-17@sha256:e4a7ace3dc0d645ed97f8d9ad0b0d3f0b14fa8d150138f27f116d7105a639b82
ARG GRADLE_JDK_IMAGE=eclipse-temurin:17-jdk@sha256:b64592d40959b4d13b218f6b06b9ab219ff8aa3dad61efd3b5f519ba4d72ef92
ARG JAVA_RUNTIME_IMAGE=eclipse-temurin:21@sha256:4d06038800655fe1211760cd561de70ef2ed7a47f5d69255e9834414602b7026
ARG BASE_IMAGE=debian:trixie-slim@sha256:a99cfc517144bc59b1978475ec53b46ecabec7e43635402ee5b77cc54cd1b20a

# ---------------------------------------------------------------- 1. neo4j community tarball
FROM ${MAVEN_IMAGE} AS neo4j-build
ARG NEO4J_VERSION=5.26.30
WORKDIR /src
COPY . .
# Upstream README.asciidoc "Building Neo4j": MAVEN_OPTS=-Xmx2048m, `mvn clean install -DskipTests -T1C`.
# -pl/-am limits the reactor to what the community tarball needs.
ENV MAVEN_OPTS="-Xmx2048m"
RUN mvn -B -q versions:set -DnewVersion="${NEO4J_VERSION}" -DgenerateBackupPoms=false -DprocessAllModules=true \
 && test "$(grep -rl --include=pom.xml -- '-SNAPSHOT' . | wc -l)" = 0 \
 && mvn -B -DskipTests -T1C install -pl packaging/standalone/standalone-community -am \
 && cp "packaging/standalone/standalone-community/target/neo4j-community-${NEO4J_VERSION}-unix.tar.gz" /neo4j.tar.gz

# ---------------------------------------------------------------- 2. APOC core
FROM ${GRADLE_JDK_IMAGE} AS apoc-build
ARG APOC_TAG=5.26.30
# annotated tag object -> peeled commit (GitHub API, 2026-10-01)
ARG APOC_TAG_OBJECT=064f8c717e93dfeb754e88ec917c60a9765116de
ARG APOC_COMMIT=a0ffb507e0fa9c3300f7fb14dc1385d4539a5abc
RUN apt-get update && apt-get install --no-install-recommends -y git
WORKDIR /apoc
RUN git -c advice.detachedHead=false clone --depth 1 --branch "${APOC_TAG}" https://github.com/neo4j/apoc . \
 && got_tag="$(git rev-parse "refs/tags/${APOC_TAG}")" \
 && got_commit="$(git rev-parse HEAD)" \
 && if [ "$got_tag" != "$APOC_TAG_OBJECT" ] || [ "$got_commit" != "$APOC_COMMIT" ]; then \
      echo "FATAL: apoc ${APOC_TAG} resolved to tag=$got_tag commit=$got_commit;" \
           "expected tag=$APOC_TAG_OBJECT commit=$APOC_COMMIT" >&2; exit 1; \
    fi
# apoc readme.adoc "Build & install": ./gradlew shadow. core/build.gradle sets archiveClassifier 'core'.
RUN ./gradlew --no-daemon :core:shadowJar \
 && cp "core/build/libs/apoc-${APOC_TAG}-core.jar" /apoc-core.jar

# ---------------------------------------------------------------- 3. runtime (generated from docker-neo4j)
FROM ${JAVA_RUNTIME_IMAGE} AS java-runtime
FROM ${BASE_IMAGE}
ARG NEO4J_VERSION=5.26.30
ENV JAVA_HOME=/opt/java/openjdk
COPY --from=java-runtime $JAVA_HOME $JAVA_HOME
ENV PATH="${JAVA_HOME}/bin:${PATH}" \
    NEO4J_TARBALL=neo4j-community-${NEO4J_VERSION}-unix.tar.gz \
    NEO4J_EDITION=community \
    NEO4J_HOME="/var/lib/neo4j" \
    LANG=C.UTF-8

COPY ./docker/local-package/* /startup/
COPY --from=neo4j-build /neo4j.tar.gz /${NEO4J_TARBALL}
COPY --from=apoc-build /apoc-core.jar /apoc-core.jar

RUN apt-get update \
    && apt-get install --no-install-recommends -o Acquire::Retries=10 -y \
      curl ca-certificates gcc libc-dev git jq make procps tini wget \
    && groupadd --gid 7474 --system neo4j \
    && useradd --uid 7474 --system --no-create-home --home "${NEO4J_HOME}" --gid neo4j neo4j \
    && tar --extract --file ${NEO4J_TARBALL} --directory /var/lib \
    && mv /var/lib/neo4j-* "${NEO4J_HOME}" \
    && mv /apoc-core.jar "${NEO4J_HOME}/labs/apoc-${NEO4J_VERSION}-core.jar" \
    && rm ${NEO4J_TARBALL} \
    && sed -i 's/Package Type:.*/Package Type: docker trixie/' $NEO4J_HOME/packaging_info \
    && mv /startup/neo4j-admin-report.sh "${NEO4J_HOME}"/bin/neo4j-admin-report \
    && mv "${NEO4J_HOME}"/data /data \
    && mv "${NEO4J_HOME}"/logs /logs \
    && chown -R neo4j:neo4j /data \
    && chmod -R 777 /data \
    && chown -R neo4j:neo4j /logs \
    && chmod -R 777 /logs \
    && chown -R neo4j:neo4j "${NEO4J_HOME}" \
    && chmod -R 777 "${NEO4J_HOME}" \
    && chmod -R 755 "${NEO4J_HOME}/bin" \
    && ln -s /data "${NEO4J_HOME}"/data \
    && ln -s /logs "${NEO4J_HOME}"/logs \
    && git clone https://github.com/ncopa/su-exec.git \
    && cd su-exec \
    && git checkout 4c3bb42b093f14da70d8ab924b487ccfbb1397af \
    && echo d6c40440609a23483f12eb6295b5191e94baf08298a856bab6e15b10c3b82891 su-exec.c | sha256sum -c \
    && echo 2a87af245eb125aca9305a0b1025525ac80825590800f047419dc57bba36b334 Makefile | sha256sum -c \
    && make \
    && mv /su-exec/su-exec /usr/bin/su-exec \
    && apt-get -y purge --auto-remove curl gcc git make libc-dev \
    && rm -rf /var/lib/apt/lists/* /su-exec


# GPL-3.0 (neo4j) + Apache-2.0 (apoc, docker-neo4j packaging). Corresponding source: this fork at the
# commit in org.opencontainers.image.revision (set by CI) plus the pinned apoc tag in stage 2.
ARG VCS_REF=unknown
LABEL org.opencontainers.image.title="pmoves-neo4j" \
      org.opencontainers.image.version="${NEO4J_VERSION}" \
      org.opencontainers.image.revision="${VCS_REF}" \
      org.opencontainers.image.licenses="GPL-3.0-only AND Apache-2.0" \
      org.opencontainers.image.source="https://github.com/POWERFULMOVES/PMOVES-neo4j" \
      org.opencontainers.image.description="Neo4j Community ${NEO4J_VERSION} + APOC core, built from source"

ENV PATH="${NEO4J_HOME}"/bin:$PATH

WORKDIR "${NEO4J_HOME}"

VOLUME /data /logs

EXPOSE 7474 7473 7687

ENTRYPOINT ["tini", "-g", "--", "/startup/docker-entrypoint.sh"]
CMD ["neo4j"]
